# Generated by Django 2.2 on 2019-07-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingCountry',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
