# Generated by Django 2.2 on 2019-07-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shippingcountry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingname',
            new_name='billingName',
        ),
    ]
